### ISSUE TITLE
韶音 TREKZ AIR——开放听音的骨传导耳机

### ISSUE THREAD

**Issue by binderclip** [binderclip/share#22]
- [AFTERSHOKZ 韶音 TREKZ AIR 骨传导运动蓝牙耳机 京东](https://item.jd.com/16636418552.html)
- [耳机一般不会影响听力，为什么还是不能戴太久？](https://mp.weixin.qq.com/s/vnfY505AsX2UluI-MEmCxw)

![box](https://user-images.githubusercontent.com/8187479/44521235-f3652500-a704-11e8-9e11-2f384b76db05.jpg)

背景：

- 先在微博上被种草
- 本来打算有机会找线下店体验的
- 后来看到芝麻信用里的信用免押活动，租借一周只要 7 块钱加自付来回运费，就下单了

特性：

- 音质
  - 比一百块的入耳式耳机的音质都要差
- 神奇的地方
  - 开机之后播放欢迎声音的时候震动的，拿在手里的感觉比较奇特
  - 戴上之后如果声音比较大，能明显的感觉到震动，有一点痒
- 还是会往外放出一些声音
  - 不全是靠骨传导
  - 堵上耳朵之后听到的这个耳机发出的声音就变小了很多
  - 在特别安静的环境中旁边的人能听到一点耳机发出的声音
- 开放听音
  - 在嘈杂的环境里完全听不清声音
    - 在餐馆是不可能听清的
    - 在车辆多的十字路口也基本听不清
  - 在安静的环境里听着耳机还能听到周围的其他突然的声音
    - 马路上听到其他车辆的声音
    - 在房间里可以听到房间外讲话的声音
- 价格不算便宜，比 AirPods 还要贵一点

可能的使用场景：

- 在路上骑车的时候一边听音乐一边能听到周围的声音，安全
- 在家、工作的时候一边听东西一边能不摘耳机直接听到周围人讲话，防止找你的人说了话你没听见，互相尴尬
- 戴入耳耳机和头戴耳机都不舒服的时候

不太合适的使用场景：

- 地铁、公交通勤或在嘈杂的环境里想隔一下噪音或者想听清楚详细内容（听 FM、看视频）的时候
- 对音质要求高的场景（欣赏音乐）

**Comment by binderclip** [comment]
👨‍💻

**Comment by x1ah** [comment]
这.....感觉能想到的使用场景有：
- 运动场跑步的时候戴着听音乐燃一点
- 骑自行车无聊听音乐
- 走路无聊听音乐

所以感觉只能用来听音乐........音乐相对不那么要求准确度和不要求不可干扰

要是走路想听个播客听个广播啥的就好像不太行了..

觉得这个骨传导耳机 可以近似等于 ***随身 mini 外放小音响***。可以用来解决 ***使用音响但是又不想太大声干扰别人*** 的场景。在一般需要使用耳机的场景这个还是没法解决。

**Comment by binderclip** [comment]
@x1ah 你说的差不多。还有就是在家里或公司用，别人喊你你可以直接听得到。
